### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by ntimo** [piwik/piwik-mobile-2#5367] opened 2017-02-08 20:30 UTC
Hello,
I wanted to ask you if you add some more material design too the app. So for example you could add a material design menu bar or a material design header bar.

That would be so so awesome and make the app not look so dated,
Timo

**Comment by tsteur** [comment] 2017-02-08 22:48
Marking it as a duplicate of https://github.com/piwik/piwik-mobile-2/issues/5318 

It would be really awesome to have but right now we are focussing on some other Piwik features. If you are interested in contributing let me know 👍

**Closed by tsteur** 2017-02-08 22:48 UTC
